'''
Created a visual ETL job in AWS Glue to process daily flight data.
This code is generated by AWS Glue Studio and is intended to be run as an ETL job.
'''

import sys
from awsglue.transforms import *
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job

args = getResolvedOptions(sys.argv, ['JOB_NAME'])
sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args['JOB_NAME'], args)

# Script generated for node AirportCodesDim
AirportCodesDim_node1748706647822 = glueContext.create_dynamic_frame.from_catalog(database="airlines", table_name="dev_airlines_dim_airport_codes", redshift_tmp_dir="s3://redshift-glue-airline/read/",additional_options={"aws_iam_role": "arn:aws:iam::028828332390:role/service-role/AmazonRedshift-CommandsAccessRole-20250531T174023"}, transformation_ctx="AirportCodesDim_node1748706647822")

# Script generated for node DailyFlightsRawFromS3
DailyFlightsRawFromS3_node1748706908469 = glueContext.create_dynamic_frame.from_catalog(database="airlines", table_name="flights_raw", transformation_ctx="DailyFlightsRawFromS3_node1748706908469")

# Script generated for node JoinForDepartureDetails
JoinForDepartureDetails_node1748706831453 = Join.apply(frame1=DailyFlightsRawFromS3_node1748706908469, frame2=AirportCodesDim_node1748706647822, keys1=["originairportid"], keys2=["airport_id"], transformation_ctx="JoinForDepartureDetails_node1748706831453")

# Script generated for node SchemaChangesForDepartureDetails
SchemaChangesForDepartureDetails_node1748707037108 = ApplyMapping.apply(frame=JoinForDepartureDetails_node1748706831453, mappings=[("carrier", "string", "carrier", "string"), ("destairportid", "long", "destairportid", "long"), ("depdelay", "long", "dep_delay", "long"), ("arrdelay", "long", "arr_delay", "long"), ("city", "string", "dep_city", "string"), ("name", "string", "dep_airport", "string"), ("state", "string", "dep_state", "string")], transformation_ctx="SchemaChangesForDepartureDetails_node1748707037108")

# Script generated for node JoinForArrivalDetails
JoinForArrivalDetails_node1748707219680 = Join.apply(frame1=SchemaChangesForDepartureDetails_node1748707037108, frame2=AirportCodesDim_node1748706647822, keys1=["destairportid"], keys2=["airport_id"], transformation_ctx="JoinForArrivalDetails_node1748707219680")

# Script generated for node SchemaChangesForArrivalDetails
SchemaChangesForArrivalDetails_node1748707273773 = ApplyMapping.apply(frame=JoinForArrivalDetails_node1748707219680, mappings=[("carrier", "string", "carrier", "string"), ("dep_state", "string", "dep_state", "string"), ("state", "string", "arr_state", "string"), ("arr_delay", "long", "arr_delay", "long"), ("city", "string", "arr_city", "string"), ("name", "string", "arr_airport", "string"), ("dep_city", "string", "dep_city", "string"), ("dep_delay", "long", "dep_delay", "long"), ("dep_airport", "string", "dep_airport", "string")], transformation_ctx="SchemaChangesForArrivalDetails_node1748707273773")

# Script generated for node WriteInTargetRedShiftTable
WriteInTargetRedShiftTable_node1748707999738 = glueContext.write_dynamic_frame.from_catalog(frame=SchemaChangesForArrivalDetails_node1748707273773, database="airlines", table_name="dev_airlines_daily_flights_processed", redshift_tmp_dir="s3://redshift-glue-airline/write/",additional_options={"aws_iam_role": "arn:aws:iam::028828332390:role/service-role/AmazonRedshift-CommandsAccessRole-20250531T174023"}, transformation_ctx="WriteInTargetRedShiftTable_node1748707999738")

job.commit()